---
version: "3"

services:
  dev:
    build: .devcontainer
    user: vscode
    init: true
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:${LOCAL_WORKSPACE_FOLDER}:cached
  hass:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .devcontainer/preconfig.sh:/etc/cont-init.d/preconfig.sh:ro
      - .devcontainer/preconfig:/preconfig.d/01-integration:ro
      - .devcontainer/config/configuration.yaml:/config/configuration.yaml:ro
      - .devcontainer/config/specific_configuration.yaml:/config/specific_configuration.yaml:ro
      - .devcontainer/config/www:/config/www
      - ./custom_components:/config/custom_components:ro
    ports:
      - 8123:8123

    privileged: true
    # network_mode: host


  frigate:
    privileged: true
    image: "ghcr.io/blakeblackshear/frigate:${FRIGATE_VERSION:-0.12.0-rc1}"
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .devcontainer/frigate.yml:/config/config.yml:ro
      - ./frigate:/media/frigate
    ports:
      - "5000:5000"

  vision_service_mqtt:
    extends:
      file: ./vision-service-mqtt-handler/docker-compose.yml
      service: vision_service_cpu
    env_file: .env

  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped

networks:
  frigate-network:
    external: true